apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:iBF10FJALbcMJ8H96mmwqWFUN7s3ryntQGxQB+JM2U5t+iKY9+AxDQ==,iv:okzmu5jksIeU5XgD3MgOuy1qXG2RCB3v6S/NT6PCHjQ=,tag:KB5AyTTAWsBdpmW+gznkNw==,type:str]
sops:
  age:
    - recipient: age1458wrvswsx7edgha2vzqxn6l4da2g45eqylphdkdrjxuqh0g3sxsgepy9e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNzBSVVhZOHpFcU1KMDRP
        ckdCTFcvTEFmVUJscENHQlVQdGZFZEVrZndBCjFWUWYyWlFtVHl1N2lMRmMrQmgy
        VnZ1QnBJSmdoa1NONGxEaHhrdFFzUGcKLS0tIEdOaTFLWGxOcFo3QXJHUHFvMElJ
        bjl1bmpPMlgyd1g4S2taQkdPRzhmVTAKzvp6oegTdecB1d0O29OKq0wvfCOzZhLl
        kV1tlRoyDVjtQJP8k2apECxmDaMc4pqUcJRavdQu86h4BW643R8zag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T11:38:38Z"
  mac: ENC[AES256_GCM,data:fc3GNnnEK1Ur1r60gfjlmGx+kWBgwHppIObbYHhvkKV0WTqS+rSBitJ5GrFZmZrgkAu28BtNZ1YdYci8vDyszry4FKYbiqftBRdeY5s+Pec43saNmnoK7M0KZvWh65dV8vgaefDWqmDlu1vVIrFGlHD5/C8cPV8uyUeNZGyg/eA=,iv:H6JoOjKvJuXgLPy9zVRpY35fh8O0kfeYShzea0sVxco=,tag:Lzk5x3JaBEXtEIeTycqsyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
