apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:skfBy3YCJBUIepE=,iv:bzawlAIuYEH76BgUnIvmQscqzVze1+i3VPTUA8ZNUzs=,tag:JzKsXFaoqK3q2+5DmiifmA==,type:str]
sops:
  age:
    - recipient: age1458wrvswsx7edgha2vzqxn6l4da2g45eqylphdkdrjxuqh0g3sxsgepy9e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UGNGbkFMR05pSDl5UGxk
        MEhGVFdHdXI2T2tKaU9WZzV4SGpEVHVYZkJVCklnVUdtZ0ZYMGtBK0ZTYWpraVVw
        a09ONjUzTU92TkVmV29RWFJ6Y3VjQXMKLS0tIG1aekxYSmxTQ1h1U2NvNncyRXJt
        bEkyNGhrdEhVblM3OE1iS3AvSGc4UUUKEm6PkORVztVMEZpAJuormC9AIBl7yxr6
        xjhN+Pngmd5MLAULAHvwBOe7M/Souf/fYAx6oA9TPgavrEHzofrsQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T11:38:38Z"
  mac: ENC[AES256_GCM,data:I8XX3/fdiXAYLukXNJXx79ROrtrR72ltCofjHRlOpEQoajc3/xzdjMxcfvUbHS0B0SIyJznLqlHdiZF8wg6zjAHHGQu9UvExUs1kCOc3aF7PCS89fNnaP1ZSv9sDTAXqGPSG6eW0+9R7PP0Cm50mmH27ATWIpWs6VCcNVDZ2qCY=,iv:E2ju3N8RNDDtf4KlJUMKXF0Ecx6P3iGbBgg0TZW952w=,tag:PBC1OSju2+N/Qs/ntG2byA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
