apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ZGz4fEITgmRiv5ndpAX3xZ1ZlsE2djB2h1pbdyvBY/I=,iv:M4gsqIOyvL3Tf7iezdYEiLp4aDbW/AjrdHij8ElWczM=,tag:NOd6mj6lAoeieif8RK6kNQ==,type:str]
sops:
  age:
    - recipient: age1458wrvswsx7edgha2vzqxn6l4da2g45eqylphdkdrjxuqh0g3sxsgepy9e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRDJwQWFkWWg0RVJjazhW
        TFR1dEQwSENOWFV2NFBndllLUmFrQWdzQkIwCnFXUDVKUStyaGYzaVNmMmRUWThK
        K25hL09nR3R1cFhCQjB0aUdUTDRSbzAKLS0tIGhyVUNDTFNuQ0xiWkw3NXdQakc2
        UTNRNzNLZlZiMHJwT2JjM2pNQ082RmsKpMaaZSDaQXqZ42Z4ssXS8LO7f9dg0X9I
        QupPUwCuHTVgsaZsPnpmiXiQNpkpt4tHioll4583+J9QuKxtlRlJ5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T11:38:38Z"
  mac: ENC[AES256_GCM,data:+F/4nxAtaW2L/mnkw+gp5fiSHCvgMI+Bts6ORQqLf/Ya0UlStHxeMwjsOMvyvtQfqSFmNS+U0eMduQkjP6kFfeESUWyI2YveX50z9rApCqI5R7t4iJtVdZm30LTHCzyOM3MApCgqjm06jdGX8cn7XMuESCrR6JZeh43jZ4ghCxQ=,iv:w2HL5aezZfQ2S1yeozIEk0hdgNLFaJ0vhOxR9MPBKuw=,tag:hmAt1O2yHAfs9+zi6GnPvg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
