apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:LRiqKczVqau1BAjU5plk6wtXfkNq1o5HVHvq3HEjhIkCZt8MGN3NioTtrBtAeX4b8kH33J4ytCWpt46xnw1uAkPItr7PZ2jOAqqwBF3tgygiORkp/+sgc4/KVv56a5UvEQpo0ixP+XqCcMMFgtaQzeC2Zpffgx1hwMCdWTAgGG9QFkEiQct5cM/xEBYTaDNM96JtZRRxYhOfrIg01MPNrm8pdwFFpP/ZLSs54WSzJDNUux5I,iv:oqFAP4mam/aj3ySU5alRaydFc2GXEHsgkES/h/Nvkqk=,tag:n0kkidyZop2hRfjSHzk3yQ==,type:str]
sops:
  age:
    - recipient: age1458wrvswsx7edgha2vzqxn6l4da2g45eqylphdkdrjxuqh0g3sxsgepy9e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcWI4RHY0d3dmNVFTNnZv
        QzJoTGp3NkUwcjZ3WUlBSy9aU1lsNTRwR0RnCkhleTRNWW81RjRoYWkvZ1pFM2Fp
        TjZJalVMSmVhUVFKenI1dzFCVjFJMlEKLS0tIG5CNmdkQzB4YjFHTG1CSG1uTkpF
        L1d6Wm1TdGlVMEZocjVoQ1lReThicG8KIMwwhsaxAYCCq0Drt1M1kXdR7EcUa8K3
        gfPUz3WE09NUpEcoWCqk+juyWpLpM0e1UERNBxBNzV8w6RN01RRl5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T11:38:38Z"
  mac: ENC[AES256_GCM,data:U7tLQcx0Vr6ziruKvkmIslDOMK3BtnbojMMTmP/jCTva8DSpzTAPCEUMSB+RgdOrAibk3uldPrpQryTiuedVWi8L+P5NpzHabV+FXSuGgrIM/lcadH5ou+muPKGNT6qeMuODib/IYSLNpni2zybZTlAS7q6WBESsTCqTPfWQ0LI=,iv:6XtGed7aacEXqaMsVJ9qjkNE8n50D6hp1Pj3Y7NJMhU=,tag:1GZ/yxiyUD7Lal+sbB+hCw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
