apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ckJKlz9i9dl7xFcv5YkaSdYj6u6rSH1OWJAp14kGJNalx1+37lLERQ==,iv:0vBfREHl9N8OR2v24KSIQzlfFgByFdcUZwMS1QN+6AA=,tag:NFah8mJ3aSG8q4B9ITyLgw==,type:str]
sops:
  age:
    - recipient: age1458wrvswsx7edgha2vzqxn6l4da2g45eqylphdkdrjxuqh0g3sxsgepy9e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVXFmK0liVGRDZmwrQ0h2
        bUtEL2l3MlBDQTA0dmFTaDBwV1lrTGdwblhRCnozWU85TGR5SEdBc1pvYVVwcUdU
        RzB0SlAzaXRlV0RBNlZDSkVjU2pUTFEKLS0tIGk0amJNK0xGblhXdk92RGtMRmQv
        UGtVYUtiWm1ONTZoR2NhdW5PeDEzbGMKpE/gmW/wZPtqoCOQYiBtEZ21UdfCoyqA
        qDE+yiS4Gq4x+6aQsmIdgqM6OfkAxT3qJG9yqqguzXsrGswrMEm8hQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T11:38:38Z"
  mac: ENC[AES256_GCM,data:Ghs6UFi0aw3JOin3yejRdH1KdjNe8TnGLjizJ8FbzYOQoCy/JOlrMrpgkJtxNUmKB/bNZISkF9A3Y0OEk7vP05tbYT5K604/BM5zLXaMhsokaQDNgsPnJayBDJu4f5TJkxMCgoQr6tjh328x1JDScRfbx36plfIh1VvwtIZ/9lg=,iv:2bXe1aHIzynB1sxd/fOU//nrAzl3cys2G2dOEpsarJM=,tag:VWMD4qm9rSct+6QxLry/LA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
